// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
	models "linephobia/backend/internal/models"
)

type Repostat struct {
	ID        pgtype.Int8
	Url       string
	Site      string
	Owner     string
	Name      string
	CreatedAt pgtype.Timestamptz
	Stats     models.LanguageSummary
}
